# Generated by Django 5.0.3 on 2024-03-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Attention Required", "Attention Required"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
